services:
  - type: web
    name: contact-api
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
